version: "3.4"

services:

  ton_proxy_service:
    build: .
    hostname: ton_proxy
    container_name: ton_proxy
    environment:
      PROXY_SERVER_ADDRESS: 78.155.217.86
      PROXY_SERVER_PORT: 8080
    ports:
      - "2731:2731"
      - "80:80"
    restart: always
